//
//  STCreationTop.m
//  ProjectName
//
//  Created by H3xept on 03/10/15.
//  Copyright (c) 2015 H3xept. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "STCreationTop.h"


@implementation STCreationTop

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.055 green: 0.445 blue: 0.709 alpha: 1];


    //// Subframes
    CGRect page1 = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame), CGRectGetHeight(frame));


    //// Page-1
    {
        //// iPhone-6
        {
            //// Rectangle-1-Copy Drawing
            UIBezierPath* rectangle1CopyPath = UIBezierPath.bezierPath;
            [rectangle1CopyPath moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.10419 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.98586 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.04665 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.99368 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.01414 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.10419 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.00633 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.04656 * CGRectGetHeight(page1))];
            [rectangle1CopyPath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1))];
            [rectangle1CopyPath closePath];
            rectangle1CopyPath.miterLimit = 4;

            rectangle1CopyPath.usesEvenOddFillRule = YES;

            [color0 setFill];
            [rectangle1CopyPath fill];
        }
    }
}

@end
