//
//  STCreationTop.h
//  ProjectName
//
//  Created by H3xept on 03/10/15.
//  Copyright (c) 2015 H3xept. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface STCreationTop : NSObject

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;

@end
