//
//  STTargetNameRectangle.m
//  ProjectName
//
//  Created by H3xept on 09/10/15.
//  Copyright (c) 2015 H3xept. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "STTargetNameRectangle.h"


@implementation STTargetNameRectangle

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color2 = [UIColor colorWithRed: 0.728 green: 0.728 blue: 0.728 alpha: 1];


    //// Subframes
    CGRect page = CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 1, CGRectGetWidth(frame) - 2, CGRectGetHeight(frame) - 2);


    //// Page-
    {
        //// target_rectangle
        {
            //// Page- 2
            {
                //// Rectangle-1 Drawing
                UIBezierPath* rectangle1Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(page) + floor(CGRectGetWidth(page) * 0.00000 + 0.5), CGRectGetMinY(page) + floor(CGRectGetHeight(page) * 0.00000 + 0.5), floor(CGRectGetWidth(page) * 1.00000 + 0.5) - floor(CGRectGetWidth(page) * 0.00000 + 0.5), floor(CGRectGetHeight(page) * 1.00000 + 0.5) - floor(CGRectGetHeight(page) * 0.00000 + 0.5)) cornerRadius: 32.5];
                [color2 setStroke];
                rectangle1Path.lineWidth = 1;
                [rectangle1Path stroke];
            }
        }
    }
}

@end
