//
//  TargetViewOutline.m
//  ProjectName
//
//  Created by H3xept on 03/03/16.
//  Copyright (c) 2016 H3xept. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "TargetViewOutline.h"


@implementation TargetViewOutline

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
	UIBezierPath* aht = [UIBezierPath bezierPathWithRoundedRect:CGRectInset(frame, 1, 1) cornerRadius:frame.size.width/2];
	[[UIColor blackColor] setStroke];
	aht.lineWidth = 1;
	[aht stroke];
}

@end
