//
//  TargetViewOutline.h
//  ProjectName
//
//  Created by H3xept on 03/03/16.
//  Copyright (c) 2016 H3xept. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TargetViewOutline : NSObject

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;

@end
